### ISSUE TITLE
Pseudo code

### ISSUE THREAD

**Issue by nobrayn** [izazw/Iza-Zamorska-Wasielak-Project-3-They-are-bored-app#16]
I'm being extra by calling this an "issue", but I'm just practising.

For a still-very-new-at-this person like me, I really need pseudo code to help me decipher a lot of what's going on, still.

Your code is laid out really nicely, though! A bit of "plain-speak" would just help me to navigate and follow the breadcrumbs, so to speak.

**Comment by izazw** [comment]
Thank you Chris! I made sure to add pseudocode.
